<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LancerNexus.Protocol</RootNamespace>
    <AssemblyName>LancerNexus.Protocol</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;MsgPack017</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.9" />
  </ItemGroup>
</Project>
